export const CREATE_PRIVATE_ROOM = 'CREATE_PRIVATE_ROOM';
export const SET_ROOM_LOADING = 'SET_ROOM_LOADING';
export const SET_ROOM = 'SET_ROOM';
export const SET_ROOM_ID = 'SET_ROOM_ID';
export const JOIN_ROOM = 'JOIN_ROOM';
export const SET_ROOM_ON_PRIVATE_JOIN = 'SET_ROOM_ON_PRIVATE_JOIN';
export const SET_ROOM_ERROR = 'SET_ROOM_ERROR';
export const SET_ROOM_NAVIGATED_FROM = 'SET_ROOM_NAVIGATED_FROM';
export const SET_ROOM_SETTINGS = 'SET_ROOM_SETTINGS';
export const SET_ROOM_ON_SETTINGS_UPDATED = 'SET_ROOM_ON_SETTINGS_UPDATED';
export const SET_ROOM_ON_USER_LEFT = 'SET_ROOM_ON_USER_LEFT';

export const OPEN_SOCKET = 'OPEN_SOCKET';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_USER_ERROR = 'SET_USER_ERROR';
